// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function NotifyMSEActive(arg1) {
  return window['go']['main']['App']['NotifyMSEActive'](arg1);
}

export function RequestLoopbackOffer() {
  return window['go']['main']['App']['RequestLoopbackOffer']();
}

export function SendSdpAnswer(arg1) {
  return window['go']['main']['App']['SendSdpAnswer'](arg1);
}

export function SetLoopbackAnswer(arg1, arg2) {
  return window['go']['main']['App']['SetLoopbackAnswer'](arg1, arg2);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
