// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow():Promise<void>;

export function NotifyMSEActive(arg1:boolean):Promise<void>;

export function NotifyMediaStarved():Promise<void>;

export function ReportPlayback(arg1:number,arg2:number):Promise<void>;

export function RequestLoopbackOffer():Promise<void>;

export function SendSdpAnswer(arg1:string):Promise<void>;

export function SetLoopbackAnswer(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;
