// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow():Promise<void>;

export function SendSdpAnswer(arg1:string):Promise<void>;

export function SetLoopbackAnswer(arg1:string,arg2:string):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;
